name: 'http://www.silverstitchcreative.com/'
favicon: null
layout_spectrum: 0.36767
typography_spectrum: 0.36901
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.5522553918417543
  lightness: 0.25
  saturation: 0.9375
  rhythmicContrast: 0.25
purpose: []
