name: 'http://www.silverstitchcreative.com/'
favicon: null
layout_spectrum: 0.8539569184649736
typography_spectrum: 0.6536024224478751
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.5522553918417543
  lightness: 0.17689049919135869
  saturation: 0.2962297135964036
  rhythmicContrast: 0.8749274604488164
purpose: []
